version: '3.8'
services:
  api:
    build: .
    container_name: be-hfl
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dockernet

networks:
  dockernet:
    external: true
